/**
 * Normalise a value coming from an in-app QR scan so the create flow accepts
 * both a plain URL and a boltcard:// deeplink.
 *
 * The programming QR generated by Bolt Card Hub / LNbits is a deeplink of the
 * form `boltcard://program?url=<url-encoded auth url>`. When it is opened with
 * the phone camera, expo-router's linking already extracts the inner `url`
 * (see app/program.tsx, which receives `params.url`). But when the *same* QR is
 * scanned with the app's own scanner, `app/scan` passes the raw scanned string
 * straight through as `result`, so the create screen used `boltcard://...` as
 * the auth URL and the request failed with "Network request failed" (the
 * boltcard:// scheme is not fetchable).
 *
 * This helper extracts and decodes the inner `url` for boltcard:// deeplinks and
 * passes any other value (https://, lnurlw://, ...) through unchanged, so
 * scanning-in-app behaves the same as opening the deeplink.
 */
export default function parseBoltcardUrl(value: string): string {
    if (typeof value !== "string") return value;
    const trimmed = value.trim();
    if (/^boltcard:\/\//i.test(trimmed)) {
        const match = trimmed.match(/[?&]url=(.+)$/i);
        if (match) {
            try {
                return decodeURIComponent(match[1]);
            } catch {
                // malformed percent-encoding — fall back to the raw captured value
                return match[1];
            }
        }
    }
    return trimmed;
}
